apiVersion: apps/v1
kind: Deployment
metadata:
  name: neos-pdf
  labels:
    app: neos-pdf
spec:
  selector:
    matchLabels:
      app: neos-pdf
  template:
    metadata:
      labels:
        app: neos-pdf
    spec:
      containers:
        - name: neos-pdf-deployment
          image: ghcr.io/naborisk/neos-pdfreader-backend:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
